##############################################################################
###  New Device has connected to the network.  let everyone know.
##############################################################################

- alias: "New device connected"
  trigger:
    - platform: event
      event_type: device_tracker_new_device

  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.alert_mode
  
    - service: script.speech_engine
      data:
        call_greeting: 1
        call_new_device: 1
      data_template: 
        person: >-
          {{ trigger.event.data.name }}
##############################################################################