- alias: Update Available
  trigger:
    - platform: state
      entity_id: sensor.up_to_date
      from: 'true'
      to: 'false'
      
  action:
    - service: script.speech_engine
      data:
        call_greeting: 1
        call_update: 1

  