automation:
##############################################################################
###  New Device has connected to the network.  let everyone know.
##############################################################################

  - alias: "New device connected"
    trigger:
      - platform: event
        event_type: device_tracker_new_device

    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.alert_mode

      - service: script.speech_engine
        data:
          call_greeting: 1
          call_new_device: 1
        data_template:
          person: >-
            {{ trigger.event.data.name }}
##############################################################################
  - alias: Shut Down
    trigger:
      - event: shutdown
        platform: homeassistant
      - event_type: homeassistant.restart
        platform: event
    action:
      - service: script.janet_speech_engine
        data:
          call_bye: 1
          call_shut_down: 1
  - alias: Start Up
    trigger:
      - event: start
        platform: homeassistant

    action:
      - service: script.janet_speech_engine
        data:
          call_greeting: 1
          call_introduction: 1

  - alias: Janet Update Available
    trigger:
      - platform: state
        entity_id: sensor.up_to_date
        from: 'true'
        to: 'false'

    action:
      - service: script.janet_speech_engine
        data:
          call_greeting: 1
          call_update: 1
